#!/usr/bin/env python3
"""Deterministically benchmark the handoff's SM120 shape/batch candidates."""
from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

import torch

import pearl_sm120_cuda


SHAPES = ((128, 128), (128, 64), (64, 128), (64, 64))
BATCHES = (1, 2, 4, 8, 16, 32, 64)


def measure(m: int, n: int, batch: int, warmup: int, iterations: int) -> dict[str, object]:
    torch.manual_seed(0x504541524C534D31 & 0xFFFFFFFF)
    a = torch.randint(-64, 65, (batch, m, 2048), device="cuda", dtype=torch.int8)
    b = torch.randint(-64, 65, (n, 2048), device="cuda", dtype=torch.int8)
    key = torch.arange(32, dtype=torch.uint8)
    target = torch.zeros(32, dtype=torch.uint8)
    os.environ["PEARL_SM120_BACKEND"] = "1"
    os.environ["PEARL_SM120_FUSED"] = "1"
    os.environ["PEARL_SM120_SEARCH_ONLY"] = "1"
    for _ in range(warmup):
        pearl_sm120_cuda.search(a, b, key, target, m, n, 2048, 1)
    torch.cuda.synchronize()
    started = time.perf_counter()
    overflow = False
    cuda_errors = 0
    for _ in range(iterations):
        result = pearl_sm120_cuda.search(a, b, key, target, m, n, 2048, 1)
        overflow = overflow or bool(result["winner_overflow"])
        cuda_errors += int(result["cuda_errors"])
    torch.cuda.synchronize()
    elapsed = time.perf_counter() - started
    free_bytes, _ = torch.cuda.mem_get_info()
    work = batch * m * n * 2048 * iterations
    return {
        "m": m, "n": n, "batch": batch, "warmup": warmup, "iterations": iterations,
        "elapsed_gpu_seconds": elapsed, "valid_candidate_work": work,
        "throughput": work / elapsed if elapsed else 0.0,
        "free_bytes": free_bytes,
        "winner_overflow": overflow, "cuda_errors": cuda_errors,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--iterations", type=int, default=100)
    parser.add_argument("--output", type=Path, default=Path("artifacts/results/sm120_tuning.json"))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    output = root / args.output
    if not torch.cuda.is_available():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps({
            "status": "blocked",
            "error": "No CUDA GPUs are available",
            "shapes": SHAPES,
            "batches": BATCHES,
            "warmup": args.warmup,
            "iterations": args.iterations,
            "results": [],
        }, indent=2) + "\n")
        raise SystemExit("No CUDA GPUs are available")
    results: list[dict[str, object]] = []
    stop_reasons: list[str] = []
    for m, n in SHAPES:
        previous = None
        for batch in BATCHES:
            result = measure(m, n, batch, args.warmup, args.iterations)
            results.append(result)
            if result["winner_overflow"]:
                stop_reasons.append(f"{m}x{n}/batch{batch}: winner queue overflow")
                break
            if result["cuda_errors"]:
                stop_reasons.append(f"{m}x{n}/batch{batch}: CUDA error")
                break
            if result["free_bytes"] < 2 * 1024**3:
                stop_reasons.append(f"{m}x{n}/batch{batch}: free GPU memory below 2 GiB")
                break
            if previous is not None and result["throughput"] <= previous["throughput"] * 1.01:
                stop_reasons.append(f"{m}x{n}/batch{batch}: throughput gain below 1 percent")
                break
            previous = result
    usable = [r for r in results if not r["winner_overflow"] and not r["cuda_errors"]]
    if not usable:
        raise SystemExit("no usable SM120 tuning result")
    usable.sort(key=lambda r: (-float(r["throughput"]), int(r["batch"]), int(r["m"]) * int(r["n"])))
    selected = usable[0]
    report = {
        "status": "complete", "shapes": SHAPES, "batches": BATCHES, "warmup": args.warmup,
        "iterations": args.iterations, "results": results, "stop_reasons": stop_reasons,
        "selected": selected,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n")
    tuning_header = root / "miner/pearl-gemm/csrc/sm120/generated_tuning.h"
    tuning_header.write_text(
        "#pragma once\n"
        "// Generated by miner/tools/tune_sm120.py; do not retune in the mining loop.\n"
        f"#define PEARL_SM120_TUNED_M {int(selected['m'])}\n"
        f"#define PEARL_SM120_TUNED_N {int(selected['n'])}\n"
        f"#define PEARL_SM120_TUNED_BATCH {int(selected['batch'])}\n"
    )
    print(json.dumps({"selected": selected, "output": str(output)}, indent=2))


if __name__ == "__main__":
    main()
